version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - db
  db:
    image: mongo
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    ports:
    - "27017:27017"