version: '3.9'

services:
  api:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 5000:80
      - 5001:443
    environment:
      ConnectionStrings__NetLogs: "Server=db,1433;Database=master;User=sa;Password=suchSecureVeryWordSoPassW0w!;"
  db:
    image: mcr.microsoft.com/mssql/server
    user: root
    volumes:
      - net-log:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "suchSecureVeryWordSoPassW0w!"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
volumes:
  net-log:
    name: net-log-db