version: "3.9"

services:
  webapp:
    build: .
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=shhsecret
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/lesson-11.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
