version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    user: root
    volumes:
      - hello-compose:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "suchSecureVeryWordSoPassW0w!"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
volumes:
  hello-compose:
    name: hello-compose-db